dist: bionic
language: rust
rust:
- stable
- beta
- nightly
matrix:
  allow_failures:
  - rust: nightly
  fast_finish: true
cache: cargo
sudo: required

addons:
  apt:
    packages:
    - libssl-dev

before_script:
- |
  if [[ "$TRAVIS_RUST_VERSION" == stable ]]; then
    export RUNTIME_MACROS_IS_MAIN_VERSION=true
    cargo install cargo-tarpaulin
  fi
  export RUSTFLAGS="--cfg procmacro2_semver_exempt"
script:
- |
  cargo clean &&
  cargo build &&
  cargo test &&
  cargo bench &&
  if [[ "$RUNTIME_MACROS_IS_MAIN_VERSION" == true ]]; then
    cargo doc
  fi
after_success:
- |
  if [[ "$RUNTIME_MACROS_IS_MAIN_VERSION" == true ]]; then
    bash <(curl https://raw.githubusercontent.com/xd009642/tarpaulin/master/travis-install.sh)
    cargo tarpaulin --ciserver travis-ci --coveralls $TRAVIS_JOB_ID
  fi
